# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://http://127.0.0.1:3000
baseurl: /
title: Mny Singh
author: Mny Singh
description: Still in the queue of wannabe
avatar: profile.png
email: manjindersingh550.ms@gmail.com
facebook: yoursmny
twitter: yoursmny
instagram: manjindersinghofficial
mobile: 8568806184   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
